### ISSUE TITLE
Fastapi Example does not work due to requirements.txt

### ISSUE THREAD

**Issue by NJannasch** [cloudflare/python-workers-examples#1]
Hi folks,

Amazing to see python capabilities inside cf workers!

I was playing around with this repo and unfortunately it is not possible to deploy the fastapi example although its promoted in several areas. Am I doing something wrong? If not - is there a timeline available when all the examples in this repository can be tested? Thank you!

![image](https://github.com/cloudflare/python-workers-examples/assets/9076687/6a06a3e5-d271-4592-8b58-2033f3c28a66)

Edit: dev works fine - only deployment does not work

**Comment by irvinebroque** [comment]
Hey @NJannasch — you can run all of the examples locally — which uses the Workers runtime under the hood.

As noted in the [docs](https://developers.cloudflare.com/workers/languages/python/) and error message — you can't quite yet deploy the example apps in this repository that have a `requirements.txt` file. You'll be able to do so soon — next few weeks.

**Comment by irvinebroque** [comment]
Updated docs
