### ISSUE TITLE
How do you deploy with FastAPI for Python worker

### ISSUE THREAD

**Issue by laike9m** [cloudflare/python-workers-examples#8]
I want to deploy a Python worker built with FastAPI (say this [example](https://github.com/cloudflare/python-workers-examples/tree/main/03-fastapi)), but got this error running `npx wrangler@latest deploy`

> You cannot yet deploy Python Workers that depend on packages defined in requirements.txt. Support
  for Python packages is coming soon. [code: 10021]
> If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

I found this relevant issue filed for workers-sdk: https://github.com/cloudflare/workers-sdk/issues/5608, which claimed that this is **not planned** for wrangler.

Is it true that, **cloudflare claims to support many [3rd-party packages ](https://developers.cloudflare.com/workers/languages/python/packages/) in Python worker, but you cannot deploy them, in any way?**

**Comment by dom96** [comment]
You cannot deploy them _yet_, it is planned and we are working on making this possible soon.
